export const initialTeams = [
    {
        id: 1,
        name: "ACCIN VORTEX (ARG)",
        players: [
            { id: 1, number: 1, name: "JORGE SEGURA", role: "PITCHER", placeOfBirth: "GUATEMALA", teamId: 1 },
            { id: 2, number: 2, name: "JUAN DIEGO MORALES", role: "PITCHER", placeOfBirth: "GUATEMALA", teamId: 1 },
            { id: 3, number: 3, name: "JUAN JOSÉ PEPE", role: "PITCHER", placeOfBirth: "ARGENTINA", teamId: 1 },
            { id: 4, number: 14, name: "LEONARDO BRESS", role: "PITCHER", placeOfBirth: "ARGENTINA", teamId: 1 },
            { id: 5, number: 27, name: "LUIS TORREJÓN", role: "CATCHER", placeOfBirth: "ARGENTINA", teamId: 1 },
            { id: 6, number: 4, name: "FAUSTO SIVIERO", role: "CATCHER", placeOfBirth: "ARGENTINA", teamId: 1 },
            { id: 7, number: 52, name: "MANUEL GODOY", role: "INFIELDER", placeOfBirth: "ARGENTINA", teamId: 1 },
            { id: 8, number: 8, name: "FEDERICO OLHEISER", role: "INFIELDER", placeOfBirth: "ARGENTINA", teamId: 1 },
            { id: 9, number: 10, name: "FRANCO ORTELLADO", role: "INFIELDER", placeOfBirth: "ARGENTINA", teamId: 1 },
            { id: 10, number: 5, name: "FELIPE MUÑOZ", role: "INFIELDER", placeOfBirth: "ARGENTINA", teamId: 1 },
            { id: 11, number: 66, name: "NAHIM BRAHIM", role: "OUTFIELDER", placeOfBirth: "ARGENTina", teamId: 1 },
            { id: 12, number: 7, name: "JUNIOR GUAPE", role: "OUTFIELDER", placeOfBirth: "ARGENTINA", teamId: 1 },
            { id: 13, number: 8, name: "LAUTARO FERRARA", role: "OUTFIELDER", placeOfBirth: "ARGENTINA", teamId: 1 },
            { id: 14, number: 13, name: "MARCOS PORCO", role: "OUTFIELDER", placeOfBirth: "ARGENTINA", teamId: 1 },
            { id: 15, number: 31, name: "LAUTARO GARCÍA", role: "OUTFIELDER", placeOfBirth: "ARGENTINA", teamId: 1 },
            { id: 16, number: 32, name: "JOSÉ DORANTES", role: "UTILITY", placeOfBirth: "VENEZUELA", teamId: 1 },
            { id: 17, number: 82, name: "GUSTAVO GODOY", role: "COACH", placeOfBirth: "ARGENTINA", teamId: 1 },
            { id: 18, number: 18, name: "ÁLVARO QUISPE", role: "COACH", placeOfBirth: "ARGENTINA", teamId: 1 },
            { id: 19, number: 33, name: "CHRISTIAN RIAL", role: "TEAM PRINCIPAL", placeOfBirth: "ARGENTINA", teamId: 1 },
            { id: 20, number: 6, name: "IVÁN FURMAN", role: "HEAD COACH", placeOfBirth: "ARGENTINA", teamId: 1 },
            { id: 21, number: 22, name: "MARIO PORCO", role: "HEAD COACH", placeOfBirth: "ARGENTINA", teamId: 1 },
        ]
    },
    { id: 2, name: "CACIQUES BY SWING (CHI)", players: [] },
    { id: 3, name: "CITY PAN (CHI)", players: [] },
    { id: 4, name: "MAYO'S (MEX)", players: [] },
    { id: 5, name: "SOUTH ARGENTINA (ARG)", players: [] },
    { id: 6, name: "TEAM FINCA JUJURE (VEN)", players: [] },
];

export const initialGames = [
    { id: 1, team1Id: 2, team2Id: 4, day: "DÍA 1: Miércoles, 18 de marzo", time: "10:15", score1: 8, hits1: 10, errors1: 1, score2: 9, hits2: 11, errors2: 0, innings: [["1", "2"], ["1", "0"], ["1", "1"], ["1", "1"], ["1", "1"], ["1", "1"], ["1", "1"], ["1", "2"]], battingStats: [], pitchingStats: [] },
    { id: 2, team1Id: 1, team2Id: 6, day: "DÍA 1: Miércoles, 18 de marzo", time: "13:15", score1: 5, hits1: 7, errors1: 2, score2: 7, hits2: 9, errors2: 1, innings: [["1", "0"], ["0", "0"], ["1", "1"], ["1", "0"], ["0", "1"], ["1", "5"], ["1", "X"]], battingStats: [], pitchingStats: [] },
    { id: 3, team1Id: 3, team2Id: 5, day: "DÍA 1: Miércoles, 18 de marzo", time: "16:15", score1: 3, hits1: 3, errors1: 3, score2: 4, hits2: 4, errors2: 4, innings: [["1", "0"], ["0", "0"], ["1", "0"], ["1", "0"], ["0", "0"], ["0", "4"], ["0", "X"]], battingStats: [], pitchingStats: [] },
    { id: 4, team1Id: 1, team2Id: 5, day: "DÍA 1: Miércoles, 18 de marzo", time: "21:00", score1: null, score2: null, innings: [], battingStats: [], pitchingStats: [] },
    { id: 5, team1Id: 3, team2Id: 6, day: "DÍA 2: Jueves, 19 de marzo", time: "10:15", score1: null, score2: null, innings: [], battingStats: [], pitchingStats: [] },
    { id: 6, team1Id: 2, team2Id: 5, day: "DÍA 2: Jueves, 19 de marzo", time: "13:15", score1: null, score2: null, innings: [], battingStats: [], pitchingStats: [] },
    { id: 7, team1Id: 4, team2Id: 1, day: "DÍA 2: Jueves, 19 de marzo", time: "16:15", score1: null, score2: null, innings: [], battingStats: [], pitchingStats: [] },
    { id: 8, team1Id: 3, team2Id: 2, day: "DÍA 2: Jueves, 19 de marzo", time: "21:00", score1: null, score2: null, innings: [], battingStats: [], pitchingStats: [] },
    { id: 9, team1Id: 5, team2Id: 6, day: "DÍA 3: Viernes, 20 de marzo", time: "10:15", score1: null, score2: null, innings: [], battingStats: [], pitchingStats: [] },
    { id: 10, team1Id: 4, team2Id: 3, day: "DÍA 3: Viernes, 20 de marzo", time: "13:15", score1: null, score2: null, innings: [], battingStats: [], pitchingStats: [] },
    { id: 11, team1Id: 2, team2Id: 1, day: "DÍA 3: Viernes, 20 de marzo", time: "16:15", score1: null, score2: null, innings: [], battingStats: [], pitchingStats: [] },
    { id: 12, team1Id: 6, team2Id: 4, day: "DÍA 3: Viernes, 20 de marzo", time: "21:00", score1: null, score2: null, innings: [], battingStats: [], pitchingStats: [] },
    { id: 13, team1Id: 1, team2Id: 3, day: "DÍA 4: Sábado, 21 de marzo", time: "12:00", score1: null, score2: null, innings: [], battingStats: [], pitchingStats: [] },
    { id: 14, team1Id: 6, team2Id: 2, day: "DÍA 4: Sábado, 21 de marzo", time: "15:00", score1: null, score2: null, innings: [], battingStats: [], pitchingStats: [] },
    { id: 15, team1Id: 5, team2Id: 4, day: "DÍA 4: Sábado, 21 de marzo", time: "18:00", score1: null, score2: null, innings: [], battingStats: [], pitchingStats: [] },
];
